name: Daily Weather Data Update

on:
  schedule:
    # Runs daily at 10:00 AM UTC
    - cron: '0 10 * * *'
  workflow_dispatch:
    # Allows manual triggering of the workflow

jobs:
  update-weather:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Check out the repository
      - name: Clone Repository
        uses: actions/checkout@v3

      # Step 2: Run the weather.sh script
      - name: Execute weather.sh
        run: |
          chmod +x weather.sh
          ./weather.sh

      # Step 3: Commit and push changes
      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update weather data"
          git push
