name: Weather Data Automation

on:
  schedule:
    # Runs every day at 10 AM UTC (adjust for your time zone if needed)
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows manual triggering

jobs:
  update-weather:
    runs-on: ubuntu-latest # Linux virtual machine

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3 # Clones the repository

    - name: Run weather.sh Script
      run: ./weather.sh # Ensure this script has executable permissions (chmod +x)

    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Update weather data [skip ci]" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Auth token for push access
