name: Weather Data Update

on:
  schedule:
    # Runs at 10am UTC daily
    - cron: '0 10 * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  weather_data:
    runs-on: ubuntu-latest # Use a Linux (Ubuntu) virtual machine

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Run the weather.sh script
      - name: Run Weather Script
        run: |
          chmod +x weather.sh # Ensure script is executable
          ./weather.sh
